version: 2
updates:

  - package-ecosystem: gomod
    directory: "/"
    target-branch: "main"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      time: "04:00"
    open-pull-requests-limit: 10
