verbose: false
go:
  version: 1.12
  cgo: false
repository:
  path: github.com/ContainerSolutions/locust_exporter
build:
  flags: -a -tags netgo
  ldflags: |
    -s
    -X {{repoPath}}/version.Version={{.Version}}
    -X {{repoPath}}/version.Revision={{.Revision}}
    -X {{repoPath}}/version.Branch={{.Branch}}
    -X {{repoPath}}/version.BuildUser={{user}}@{{host}}
    -X {{repoPath}}/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  prefix: .
  files:
    - LICENSE
crossbuild:
  platforms:
    - linux/amd64
    - linux/386
