name: Deploy Main

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - pperzyna/update-pipelines

env:
  REGISTRY: containersol/locust_exporter

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: '^1.12'

      - name: Build
        run: make build

      - name: Container - Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Container - Build    
        run: docker build -t ${{ env.REGISTRY }}:latest .

      - name: Container - Push    
        run: docker push ${{ env.REGISTRY }}:latest
